package com.main.ecommerceprototype.CMS;

public enum PageType {
    HEADER,
    FOOTER,
    LANDING_PAGE,
    LANDING_PAGE_CONTAINER_PAGE,
    PRODUCT_DETAIL_PAGE,
    PRODUCT_LIST_PAGE,
    PRODUCT_LIST_PAGE_CONTAINER_PAGE,
    CART_PAGE,
    CART_CONTAINER_PAGE,
    CHECKOUT_PAGE,
    ORDER_CONFIRMATION_PAGE,
    ORDER_HISTORY_CONTAINER_PAGE,
    ORDER_DETAIL_PAGE,
    ACCOUNT_PAGE,
    ACCOUNT_DETAILS_CONTAINER_PAGE,
    LOGIN_PAGE,
    REGISTER_PAGE,
    RESET_PASSWORD_PAGE,
    SET_PASSWORD_PAGE,
    GUIDE_PAGE,
    SUPPORT_PAGE
}
